### ISSUE TITLE
【生徒側】学習履歴  日付（月日だけ） 時間　 内容  →クリックすると詳細へ、メモが閲覧できるのと、削除や編集が可能  過去10件の履歴だけが見れる。その下に過去の履歴を見る、で過去の履歴一覧ページへ。

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#15]

**Comment by kt0319** [comment]
修正ずみ
問題なければクローズしてください。

**Comment by endoTakashi** [comment]
動き問題ないです！
詳細と編集のボタンがありますが、編集をなくして、その履歴をクリックすると詳細ページにいくように出来ますか？

**Comment by kt0319** [comment]
修正しました

**Comment by endoTakashi** [comment]
ありがとうございます！
登録時にメモが登録出来ないのと、下記の隙間調整お願いします。

<img width="105" alt="スクリーンショット 2019-04-06 11 53 19" src="https://user-images.githubusercontent.com/16441533/55664035-ad5b6c80-5862-11e9-8a40-848590caf7d0.png">

**Comment by endoTakashi** [comment]
<img width="333" alt="スクリーンショット 2019-04-06 11 54 21" src="https://user-images.githubusercontent.com/16441533/55664037-c2380000-5862-11e9-9518-2c22a73563aa.png">

**Comment by kt0319** [comment]
修正しました！
