### ISSUE TITLE
【生徒】学習統計、学習グラフ  UIを参考のものに近くなるように

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#16]
![写真 2019-04-05 15 20 32](https://user-images.githubusercontent.com/16441533/55609881-b8f45800-57bc-11e9-9268-07545ccc027d.jpg)
![写真 2019-04-05 15 20 48](https://user-images.githubusercontent.com/16441533/55609882-b8f45800-57bc-11e9-8753-b7d0f467201d.jpg)
![写真 2019-04-05 15 21 04](https://user-images.githubusercontent.com/16441533/55609883-b98cee80-57bc-11e9-856b-e0e1416cb908.jpg)

**Comment by kt0319** [comment]
ある程度合わせてみましたが、問題点がある場合には言って下さい。

**Comment by kt0319** [comment]
週の時の画像があれば貼って下さい

**Comment by endoTakashi** [comment]
ありがとうございます！めっちゃいいです！

**Comment by endoTakashi** [comment]
![写真 2019-04-13 16 13 56](https://user-images.githubusercontent.com/16441533/56076070-3f391b80-5e07-11e9-8530-0a09b2ba9539.jpg)

**Comment by endoTakashi** [comment]
あと、すいません！ヘッダーを下記に感じにお願いします。

<img width="361" alt="スクリーンショット 2019-04-13 16 11 54" src="https://user-images.githubusercontent.com/16441533/56076078-58da6300-5e07-11e9-84ab-01fdd727675c.png">

**Comment by kt0319** [comment]
ヘッダのデザインを合わせました。

**Comment by kt0319** [comment]
週別・月別のグラフを追加しました。

**Comment by endoTakashi** [comment]
ありがとうございます！

↓難しかったら無しでも大丈夫です。

全て分表示なので、１時間を超えると、「１時間」「１時間１５分」「１時間３０分」
といった表示に変わるようにできないでしょうか。

**Comment by kt0319** [comment]
時間を表示するようにしました。

**Comment by endoTakashi** [comment]
ありがとうございます！僕の伝え方が不足していました、、、グラフのほうの話をしていおりました。。

<img width="380" alt="スクリーンショット 2019-04-16 0 21 19" src="https://user-images.githubusercontent.com/16441533/56144629-b1fbef80-5fdd-11e9-9ca9-03997eb93cd8.png">

**Comment by kt0319** [comment]
修正しました。
