### ISSUE TITLE
【スクール】カラーピッカーでカラー選択が出来るように

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#20]

**Comment by kt0319** [comment]
こちらを実装する前に教材に対して色をつけた方が良いですか？
学習項目に色をつけた方が良いかもと思いました。
あと、使用教材の登録は廃止してもいいかと思いますが、どうでしょうか？

**Comment by endoTakashi** [comment]
１．教材の登録は、最初は確かに意味ないし消してもいいかと思ったのですが、過去に何の教材を使っていたかを残すのにちょうどいいかと思ったので残しだいです！

２．そうですね、学習項目に色がついたほうがベターです！

**Comment by kt0319** [comment]
対応ずみ
問題なければクローズお願いします。
