### ISSUE TITLE
【生徒】生徒画面にお知らせが配信されるように

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#21]

**Comment by kt0319** [comment]
ページを追加して対応ずみ
問題なければクローズしてください

**Comment by endoTakashi** [comment]
生徒側の受信が確認出来ません。

**Comment by kt0319** [comment]
受信とはメール送信のことでしょうか？

**Comment by endoTakashi** [comment]
はい、
でもメール送信確認できました。

スクールからお知らせがあったとき、
生徒側が気づけるようにしたいのですが、
アイコンの色変更か、アラート表示など、なにか対応可能でしょうか

**Comment by kt0319** [comment]
メール送信は配信日時に合わせてメールを送信する形になっていないため、まだ途中なんですが、
作成したらすぐ飛ぶ形でも良いでしょうか？
お知らせについては、既読、未読機能をつけて、生徒側のページのアイコンに未読数のバッジをつける形にしようと思います。

**Comment by endoTakashi** [comment]
作成したら即送信で大丈夫です！

**Comment by kt0319** [comment]
修正しました。問題あるようでしたら言ってください。

**Comment by endoTakashi** [comment]
ありがとうございます！
生徒側で
お知らせの詳細ページに「戻る」ボタンがほしいです。

理由
ブラウザのBackで戻ると、既読になっていない感じに見えるので

**Comment by kt0319** [comment]
生徒側にパンくずをつけました。

**Comment by endoTakashi** [comment]
ありがとうございます！
