### ISSUE TITLE
【スクール】レッスン登録にデータ添付が出来るように

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#22]

**Comment by kt0319** [comment]
データは画像でいいですか？
動画の場合だと容量食うのでAWSの料金が高くなる可能性があります。

**Comment by endoTakashi** [comment]
画像で大丈夫です！

**Comment by kt0319** [comment]
対応ずみ
問題なければクローズしてください

**Comment by endoTakashi** [comment]
登録の仕様は今のままで大丈夫なので、
ダウンロードが出来るようにお願いします。

レッスン、プログレスチェック、テスト、全て

**Comment by kt0319** [comment]
アップロードされた画像をダウンロード可能にしました。
