### ISSUE TITLE
生徒側　週の記録がほしいっす！

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#24]
週に何時間やっているのかが見える必要があるので、すいません、お願いします！

<img width="359" alt="スクリーンショット 2019-04-13 15 49 03" src="https://user-images.githubusercontent.com/16441533/56075831-ddc37d80-5e03-11e9-8fb4-56ba8478bc6f.png">

**Comment by kt0319** [comment]
修正ずみ

**Comment by endoTakashi** [comment]
ありがとうございます。
そして、本当に申し訳ないのですが、

スマホで閲覧している時に、総計を消したいのでお願いします。スマホだけ、というのが難しい場合には、PC閲覧時も消えて大丈夫です。

**Comment by kt0319** [comment]
総計を削除しました
