### ISSUE TITLE
生徒側　何か変なものが、、

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#25]
クリックすると、打ち消し線が入る、謎のコンテンツがありました。
<img width="345" alt="スクリーンショット 2019-04-13 15 49 33" src="https://user-images.githubusercontent.com/16441533/56075837-f59b0180-5e03-11e9-922e-77620f0fbae2.png">

**Comment by kt0319** [comment]
円グラフの項目のON/OFFだと思います。不要ならばそれができないようにします。

**Comment by kt0319** [comment]
スマホだと円グラフ自体見えないかも。

**Comment by kt0319** [comment]
現在、スマホでも円グラフが見えるように修正しました。

**Comment by endoTakashi** [comment]
こちらでは、どの環境でも円グラフが見えないですね。なんででしょう、

**Comment by kt0319** [comment]
確認した環境はどのような環境でしょうか？
osとブラウザなどを教えてください。
また、shiftを押しながら更新するなどのスーパーリロードを試してみてください。

**Comment by endoTakashi** [comment]
クローム
iPhoneSE（サファリ

それぞれ環境が古いとかではないと思います。

リロード系も試してますが変わりません。

**Comment by endoTakashi** [comment]
<img width="345" alt="スクリーンショット 2019-04-14 11 47 44" src="https://user-images.githubusercontent.com/16441533/56087699-27b36e80-5eab-11e9-9589-9d89454fe55a.png">

今の状態です

**Comment by endoTakashi** [comment]
![写真 2019-04-14 11 48 52](https://user-images.githubusercontent.com/16441533/56087714-592c3a00-5eab-11e9-8602-43495f517fa6.png)

**Comment by kt0319** [comment]
教科の表示を無くしてみました。現状どうでしょうか？

**Comment by endoTakashi** [comment]
教科のテキストがなくなっただけですね
円グラフは表示されていません。

**Comment by endoTakashi** [comment]
もし手こずりそうであれば、円グラフは全然なくても大丈夫なので、クローズしても問題ないです！

**Comment by kt0319** [comment]
横画面にしてみても見えないですか？それでも何も見えないようならば消します。

**Comment by endoTakashi** [comment]
だめですね、、消しましょう！
