### ISSUE TITLE
セッションが切れているときに、登録すると

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#33]

**Comment by endoTakashi** [comment]
![写真 2019-04-17 23 11 28](https://user-images.githubusercontent.com/16441533/56294712-7b051580-6166-11e9-81f2-7182d2890d70.png)

ログインページに戻るようにしたいです。

あと、セッションが24時間もたないですね。毎回アクセスするたびにログインを求められてしまうのですが、ログイン状態を維持出来るようにできますか？

**Comment by kt0319** [comment]
すいません。セッションタイムアウトを設定し直しました。
セッション切れの時にログイン画面に遷移するようにしました。
