### ISSUE TITLE
ラーニングレビュー変更点

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#35]
日付の登録

画像の登録

が出来るように

**Comment by kt0319** [comment]
こちらの日付はなんの日付でしょうか？
データを作った作成日時などでいいでしょうか？

**Comment by endoTakashi** [comment]
レッスンと同様に、レビューを行った日を記録したいのですが、項目名としては、「実施日」または「日付」などがいいです。

**Comment by kt0319** [comment]
画像の登録はできると思いますが、何か要望がありますか？

**Comment by kt0319** [comment]
@endoTakashi 
実施日の登録を追加しました。
