### ISSUE TITLE
詳細ページに行こうとするとバグる

### ISSUE THREAD

**Issue by endoTakashi** [endoTakashi/learnpot2#38]
スクールの管理画面

info@learn-gate.com
learngate1022

高崎 健太郎の詳細ページに行こうとするとバグります。
http://3.18.90.117/school/student/85

ご確認お願い致します。

<img width="1250" alt="スクリーンショット 2019-04-23 12 02 25" src="https://user-images.githubusercontent.com/16441533/56550113-b4eb7700-65bf-11e9-8360-82029b7c1899.png">

**Comment by kt0319** [comment]
修正しました。

**Comment by kt0319** [comment]
修正済
